language: node_js
node_js:
  - "12"

services:
  - docker

git:
  depth: false

env:
  global:
  - IMAGE="opensplit/frontend"

branches:
  only:
    - master
    - development

before_script:
  - yarn install

script:
  - if [ ${TRAVIS_BRANCH} == master ] ; then ENV=production IMAGE_TAG=stable; else ENV=staging IMAGE_TAG=development; fi
  - yarn run lint
  - yarn build --mode $ENV

after_success:
  - docker build --build-arg ENV=$ENV -t $IMAGE:$IMAGE_TAG .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $IMAGE:$IMAGE_TAG

deploy:
 - provider: script
   script: curl -X POST $WEBHOOK_DEV
   on:
     branch: development

 - provider: script
   script: curl -X POST $WEBHOOK_PROD
   on:
     branch: master

notifications:
  email: false