language: node_js
node_js:
  - "10"

services:
  - docker

env:
  global:
  - IMAGE="opensplit/frontend"

branches:
  only:
    - master
    - development
    - /^greenkeeper/.*$/

before_script:
  - npm install

script:
  - npm run lint

after_success:
  - if [ ${TRAVIS_BRANCH} == master ] ; then ENV=production IMAGE_TAG=stable; else ENV=staging IMAGE_TAG=development; fi
  - cp config/$ENV.js config/prod.env.js
  - docker build -t $IMAGE:$IMAGE_TAG .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push $IMAGE:$IMAGE_TAG

notifications:
  email: false

